name: Planning and apply infrastructure

on:
  push:
    branches: main 
jobs:
  apply:
    defaults:
      run:
        working-directory: ${{ vars.TF_ACTIONS_WORKING_DIR }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get the image URI from the build job
      run: |
        IMAGE_DIGEST=$(aws ecr describe-images --repository-name ${{ vars.INGESTION_LAMBDA_ECR }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
        echo "INGESTION_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_ENV"
    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -var="ingestion_lambda_image_uri=${{ env.INGESTION_IMAGE }}" -no-color -auto-approve