name: Deploy ingestion lambda image
on:
  push:
    paths:
      - 'ingestion/src/**'
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build-image:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - uses: hashicorp/setup-terraform@v3
   - uses: aws-actions/configure-aws-credentials@v2
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-west-2

   - name: Login to Amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v2

   - name: Create ECR repository if it doesn't exist
     run: |
       aws ecr describe-repositories --repository-names ${{ vars.INGESTION_LAMBDA_ECR }} || aws ecr create-repository --repository-name ${{ vars.INGESTION_LAMBDA_ECR }}
   
   - name: Build, tag, and push image to Amazon ECR
     id: build-image
     working-directory: ./ingestion/src
     env:
       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       ECR_REPOSITORY: ${{ vars.INGESTION_LAMBDA_ECR }}
       IMAGE_TAG: latest
     run: |
       # Build a docker container and
       # push it to ECR so that it can
       # be deployed to ECS.
       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG